spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
      username: admin
      password: pass
      authentication-database: admin
      auto-index-creation: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
          multiplier: 1
          max-interval: 300000

rabbitmq:
  consumer:
    payment-confirmed: ${PAYMENT_CONFIRMED:payment-aproved-ms-pix}
    payment-expired: ${PAYMENT_EXPIRED:payment-expired-ms-pix}


storage:
  s3:
    bucket: ifood-teste
    region: us-east-2
    directoryPhotos: catalago
    idKeyAccess: AKIA6ODU3YWAF2P7D3ZH
    keyAccessSecret: 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
